## Synthetic population pipeline for Corsica
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: cache

# This section defines which parts of the pipeline should be run
run:
  - synthesis.output # To create the output population in the output_path (see below)
  - matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: [processes]

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: [hts]

  # Define sampling rate and random seed for the output population
  sampling_rate: [sampling_rate]
  random_seed: [random_seed]

  # Paths to the input data and where the output should be stored
  data_path: /path/to/my/data
  output_path: output
  output_prefix: corsica_

  # Only interesting if you run the simulation
  java_memory: [java_memory]

  # Activate if you want to run mode choice
  mode_choice: false

  # Corsica settings
  regions: [94]
  gtfs_path: gtfs_corsica
  osm_path: osm_corsica
  ban_path: ban_corsica
  bdtopo_path: bdtopo_corsica
  matching_minimum_observations: 5