# General pipeline settings
working_directory: /odtp/odtp-workdir/cache
flowchart_path: /odtp/odtp-workdir/output/flowchart.json
dryrun: false

# Requested stages
run:
  - synthesis.population.enriched
  - matsim.output

# These are configuration options that we use in the pipeline
config:
  threads: 4
  osmosis_binary: /tmp/osmosis/bin/osmosis
  maven_binary: /tmp/maven/apache-maven-3.6.3/bin/mvn
  random_seed: 0
  hot_deck_matching_runners: 2
  disable_progress_bar: false
  java_memory: 10G
  input_downsampling: 0.01
  enable_scaling: true
  scaling_year: 2020
  use_freight: true
  hafas_date: 01.10.2018
  data_path: /odtp/odtp-workdir/data
  output_path: /odtp/odtp-workdir/output
  output_id: test
